### ISSUE TITLE
Issue with Module - just won't load for me.

### ISSUE THREAD

**Issue by r4zi3lrrr** [htilburgs/MMM-MyPrayerTimes#16]
Hi,

I've tried all sorts of variations of the config but it just won't work.

Any help would be much appreciated, please.

Just to add if I exclude the module from my config MagicMirror works fine (it's probably something that I'm doing) when adding the code into the config.

Please see my config below:

},
		{
			module: "compliments",
			position: "lower_third"
		},
		
{	
module: "MMM-MyPrayerTimes",
position: "bottom_right",
header: "My Prayer Times",
config: {
mptLat: 48.720737, // Replace with the latitude of your location
mptLon: 9.117297, // Replace with the Longitude of your location
mptMethod: 4, // Which calculation methode is used, see options below

}
},
		
Error Below:> magicmirror@2.27.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2024-06-18 18:40:30.690] [LOG]   Starting MagicMirror: v2.27.0 
[2024-06-18 18:40:30.890] [LOG]   Loading config ... 
[2024-06-18 18:40:30.902] [LOG]   config template file not exists, no envsubst 
[2024-06-18 18:40:30.923] [LOG]   Loading module helpers ... 
[2024-06-18 18:40:30.928] [LOG]   No helper found for module: alert. 
[2024-06-18 18:40:32.067] [LOG]   Initializing new module helper ... 
[2024-06-18 18:40:32.070] [LOG]   Module helper loaded: updatenotification 
[2024-06-18 18:40:32.073] [LOG]   No helper found for module: clock. 
[2024-06-18 18:40:32.683] [LOG]   Initializing new module helper ... 
[2024-06-18 18:40:32.686] [LOG]   Module helper loaded: calendar 
[2024-06-18 18:40:32.690] [LOG]   No helper found for module: compliments. 
[2024-06-18 18:40:35.734] [ERROR] (node:4279) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/admin/MagicMirror/modules/MMM-MyPrayerTimes/node_helper.js
- /home/admin/MagicMirror/js/app.js
- /home/admin/MagicMirror/js/electron.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:115476)
    at Module._resolveFilename (/home/admin/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/admin/MagicMirror/modules/MMM-MyPrayerTimes/node_helper.js:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at loadModule (/home/admin/MagicMirror/js/app.js:183:19)
(Use `electron --trace-warnings ...` to show where the warning was created) 
[2024-06-18 18:40:35.738] [ERROR] (node:4279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by htilburgs** [comment]
I know what is going on. I’ll will try to give you 2 answers for this, but that won’t be until tomorrow. 
regards Harm Tilburgs

**Comment by r4zi3lrrr** [comment]
Thank you for looking into this issue - be awesome to get it working on my MM.

**Comment by htilburgs** [comment]
Problem: Nodejs Request is Deprecated!
As of Feb 11th 2020, request is fully deprecated. No new changes are expected land.

I have to rewrite my node_helper.js module.
I'm going to do this, but not now. Not enough time and knowledge. Has to read about changing request into got.

For now I've added the request v 2.88.2 to the package.json file.
When you install MMM-MyPrayerTimes and do a NPM INSTALL then request will be added.
What do you have to do write now:

- do `cd ~/MagicMirror/Modules/MMM-MyPrayerTimes`
- do `git pull` to update the module with the latest changes
- do `npm install` to add the request nodejs module

After this the module should work as expected.

**Comment by r4zi3lrrr** [comment]
Tried the above and the module is now working :)

Many thanks for looking into this issue and for creating this module.

**Comment by htilburgs** [comment]
You’re welcome.  As I told you I’ve to do a rewrite. But until then this will work fine.

**Comment by htilburgs** [comment]
Updated MMM-MyPrayerTimes to v2.0
rewrite of `node_helper.js` to remove request and use fetch

Just do a `git pull` in de ~\MagicMirror\modules\MMM-MyPrayerTimes to update

**Comment by r4zi3lrrr** [comment]
Thank you for the update - the module is all up and running.

**Comment by totofroto** [comment]
For me, it doesn’t load.

**Comment by htilburgs** [comment]
@totofroto 
Please open new issue and tell me why it doesn't load for you.
Do you get any error messages?
This is to litle information for me to look into it.

**Comment by htilburgs** [comment]
@totofroto 
I've checked the module and did a little update.
Can you check now if it works for you?

**Comment by totofroto** [comment]
> @totofroto I've checked the module and did a little update. Can you check now if it works for you?

it works perfect now, thanks

**Comment by htilburgs** [comment]
You’re welcome. Enjoy the module.
